version: '3'

services:
    app:
        build: .
        container_name: boavista-challenge
        volumes:
            - .:/var/www
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s java -jar ./boavista-challenge-1.0.0.jar
        ports:
            - "8080:8080"
        networks:
            - app-network
        depends_on:
            - db
    db:
        build: .docker/mysql
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        #entrypoint: /etc/mysql/entrypoint.sh
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql/files:/etc/mysql
        environment:
            - MYSQL_DATABASE=boavista_challenge
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_USER=root
        networks:
            - app-network
networks:
    app-network:
        driver: bridge